-- MySQL Script generated by MySQL Workbench
-- Wed Oct 20 22:30:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `BankAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankAccount` ;

CREATE TABLE IF NOT EXISTS `BankAccount` (
  `idBankAccount` CHAR(21) NOT NULL,
  `balance` DECIMAL NOT NULL,
  PRIMARY KEY (`idBankAccount`));

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
    `idUser` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(32) NOT NULL,
    `email` VARCHAR(64) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `hq` VARCHAR(64) NOT NULL,
    `founded` DATE NOT NULL,
    `bankAccount` CHAR(21) NOT NULL,
    PRIMARY KEY (`idUser`),
    FOREIGN KEY (bankAccount) REFERENCES BankAccount(idBankAccount));


-- -----------------------------------------------------
-- Table `Bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bill` ;

CREATE TABLE IF NOT EXISTS `Bill` (
  `idBill` VARCHAR(8) NOT NULL,
  `buyer` INT NOT NULL,
  `seller` INT NOT NULL,
  `price` DECIMAL NOT NULL,
  `paid` INT NOT NULL,
  `whenPaid` DATE NULL,
  `issued` DATE NOT NULL,
  PRIMARY KEY (`idBill`),
    FOREIGN KEY (buyer) REFERENCES `User`(idUser),
    FOREIGN KEY (seller) REFERENCES `User`(idUser));


-- -----------------------------------------------------
-- Table `Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transaction` ;

CREATE TABLE IF NOT EXISTS `Transaction` (
  `idTransaction` INT NOT NULL AUTO_INCREMENT,
  `payee` CHAR(21) NOT NULL,
  `payer` CHAR(21) NOT NULL,
  `amount` DECIMAL NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idTransaction`),
    FOREIGN KEY (payee) REFERENCES BankAccount(idBankAccount),
    FOREIGN KEY (payer) REFERENCES BankAccount(idBankAccount));

